 
 
 @dominio =https://chrissho97-crispy-garbanzo-5w7gv5g46462w47-8080.preview.app.github.dev

###

GET {{dominio}}/

###

GET {{dominio}}/cursos

###

# Crear Nuevo Registro 201 creado
POST {{dominio}}/cursos
Content-Type: application/json

{"nombre": "Compiladores 2", "creditos": 5}

###

# Listar registros de un id
GET {{dominio}}/cursos/1


###
#Editar un registro 204 editado

PATCH {{dominio}}/cursos/1
Content-Type: application/json

{"nombre":"Algoritmos"}

###
# Muestra los id seleccionados
GET  {{dominio}}/cursos?size=2&page=1&sort=creditos

###

#me permite acceder al fyBynombre darle el nombre

GET {{dominio}}/cursos/search/findByNombre?nombre=Algoritmos


###

GET  {{dominio}}/carreras

###

POST {{dominio}}/carreras
Content-Type: application/json

{"nombre": "Marketing"}

###

GET  {{dominio}}/carreras/2/cursos

###
GET  {{dominio}}/carreras/1/cursos

###

GET  {{dominio}}/cursos/4/carrera

